spring:
  profiles:
    active: dev
---
server:
  port: 8001
spring:
  profiles: dev
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.git.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloudDB01
    username: root
    password: root
    dbcp2:
      min-idle: 5                                                   # todo 数据库连接池的最小维持连接数
      initial-size: 5                                              # todo 初始化连接数
      max-total: 5                                                  # todo 最大连接数
      max-wait-millis: 200

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml              # todo mybatis配置文件所在路径
  type-aliases-package: com.bjlemon.springcloud.entities         # todo 所有Entity别名类所在包
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml

eureka:
  client:    # todo 客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: dept-8001.com   # todo 自定义服务名称信息
    prefer-ip-address: true   # todo 访问路径可以显示IP地址

info:
  app.name: bjlemon-microservicecloud-springcloudconfig02
  company.name: www.bjlemon.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
---
server:
  port: 8001
spring:
  profiles: test
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.git.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloudDB02
    username: root
    password: root
    dbcp2:
      min-idle: 5                                                   # todo 数据库连接池的最小维持连接数
      initial-size: 5                                              # todo 初始化连接数
      max-total: 5                                                  # todo 最大连接数
      max-wait-millis: 200

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml              # todo mybatis配置文件所在路径
  type-aliases-package: com.bjlemon.springcloud.entities         # todo 所有Entity别名类所在包
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml

eureka:
  client:    # todo 客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: dept-8001.com   # todo 自定义服务名称信息
    prefer-ip-address: true   # todo 访问路径可以显示IP地址

info:
  app.name: bjlemon-microservicecloud-springcloudconfig02
  company.name: www.bjlemon.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}